

name: GitHubActions
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run : |
          mkdir somedir
          cd somedir
          touch sometext.txt
      - run : echo " Artem Savchuk " > somedir/sometext.txt
      - run : | 
          cd somedir
          cat sometext.txt
      
      
    
       


 
          
 
          
          
          
          
          
